repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
        exclude: tests/fixtures/|migrations/
    -   id: end-of-file-fixer
        exclude: tests/fixtures/|migrations/
    -   id: trailing-whitespace
        exclude: tests/fixtures/|migrations/
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.4
    hooks:
    -   id: reorder-python-imports
        args: [--application-directories, '.:src', --py36-plus]
        exclude: docs/|example-plugin|migrations/
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: [--line-length=119]
        exclude: docs/|example-plugin|migrations/
-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--max-line-length=119]
        exclude: migrations/
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.982
    hooks:
    -   id: mypy
        exclude: docs/|example-plugin|migrations/
