version: "3.10"
services:
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_DB: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file: ./support/.env
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alexey_razmanov -d support_app_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  web:
    build: .
    command: bash -c "make full-migrate-and-run"
    environment:
      - POSTGRES_NAME: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file: ./support/.env
    ports:
      - "8000:8000"
    # env_file:
    #   - ./support/.env
    volumes:
      - .:/support
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  celery:
    restart: always
    build:
      context: .
    command: bash -c "cd support && celery -A support worker -l info"
    environment:
      - POSTGRES_NAME: ${POSTGRES_DB}
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - ./support/.env
    # env_file:
    #   - ./support/.env
    depends_on:
      - postgres
      - redis
      - web
