# Generated by Django 4.1.3 on 2022-11-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="comments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
