# Generated by Django 4.1.3 on 2022-11-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_alter_ticket_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="comments",
        ),
    ]
