# Generated by Django 4.1.2 on 2022-10-12 17:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
