# Generated by Django 4.1.3 on 2022-11-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.JSONField(null=True),
        ),
    ]
