# Generated by Django 4.1.3 on 2022-11-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_remove_ticket_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="comments",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
