# Generated by Django 4.1.2 on 2022-10-12 17:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0003_alter_ticket_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="comments",
        ),
    ]
