# Generated by Django 4.1.2 on 2022-10-12 17:43
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ticket", "0004_remove_ticket_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="reporter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customuser_id",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
