# Generated by Django 4.1 on 2022-08-31 13:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("content", models.TextField()),
                ("is_solved", models.BooleanField(default=False)),
            ],
        ),
    ]
