# Generated by Django 4.1 on 2022-08-31 13:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Topic",
            new_name="Ticket",
        ),
    ]
