# Generated by Django 4.1 on 2022-09-09 06:46
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="author",
            new_name="user_id",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="comment_arr",
        ),
    ]
