# Generated by Django 4.1 on 2022-09-09 07:10
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_rename_author_comment_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="status",
            new_name="status_id",
        ),
    ]
