# Generated by Django 4.1 on 2022-09-02 16:20
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_ticket_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="user_id",
            new_name="user",
        ),
    ]
