# Generated by Django 4.1 on 2022-09-09 07:12
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0003_rename_status_ticket_status_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="ticket_id",
            new_name="ticket",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="status_id",
            new_name="status",
        ),
        migrations.RenameField(
            model_name="ticket",
            old_name="user_id",
            new_name="user",
        ),
    ]
