# Generated by Django 4.1 on 2022-09-09 07:19
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0004_rename_ticket_id_comment_ticket_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="support.comment",
            ),
        ),
    ]
