# Generated by Django 4.1 on 2022-09-25 15:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("userauth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="time_create",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="time_update",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user "
                + "can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all "
                + "permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
