# Generated by Django 4.1 on 2022-09-25 14:49
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comment", "0001_initial"),
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ticket.ticket"
            ),
        ),
    ]
